### PR TITLE
remove incorrect HR data <10 from the graphs

### LINKED ISSUE #1173: Mi Band 3 indicates heart rate "3" a lot of the time
screenshot_20180726-001541

#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

I know it's only preliminary support, but can't hurt to drop the issue I guess since it's the first I find with this device. The firmware is 1.2.0.8, hardware version 0.18.3.4, and Gadgetbridge is 0.28.1.

Setting a periodic heart rate reading (I tried every minute and every 5) results in many or most of the reading being "3", while the others are plausible (and fairly accurate compared to my Bip, too, I suppose).

I think that maybe "3" is just an error code indicating it failed to take that particular reading reliably, but I'm obviously guessing.

### PR DESCRIPTION
**Pull request by Dikay900**
Straightforward setting the minimum for the hr data to 10 instead of 0 to definitely eliminate zeroes and out of line hr data. Maybe we could even increase the minimum to around 40? What do you think?
Maximum value seems good to me.

<details>
  <summary>Before / After</summary>
before:
screenshot_20180801-205250

after:
screenshot_20180801-205639
</details>

fixes #1173 

Would like to let #382 and #381 open since there could be more bogus stuff around according to the discussions.

### CODE REVIEW

**Comment by Dikay900** [comment]
updated screenshots so we can better see the difference

**Comment by cpfeiffer** [comment]
I completely agree that this is very unfortunate. I'm not sure that raising the minimum HR value in general for all devices is the correct solution here. Either we should make the value configurable or we should special case it for Mi Band 3.

**Comment by Dikay900** [comment]
ok i will look into make it a configurable value, although i do not see where this value which is also used for checking whether we got a appropriate Heart Rate should not be raised to something like 30/40 in general.

**Comment by ashimokawa** [comment]
Honestly I think it is ok to merge this as is. It wont change the raw database at all, we can still do something else later. And HR 10 is obviously not healthy ;)

**Comment by cpfeiffer** [comment]
Thanks a lot. Unfortunately I still cannot merge this as is, because access to the preferences twice for every single sample would be a bit of a performance hit. The class is also used in GPXExporter, where hr is verified for every single trackpoint.

So we would need a cached version of the values and a preferences listener that updates them. Maybe we then need an instance of the HeartRateUtils class instead of just the static method.

Let me know if I should take this over or if you want to have a go at it.

**Comment by Dikay900** [comment]
Thanks for the hint i did miss the usage in the GPXExporter class so this is indeed an issue. I will solve this later.

**Comment by Dikay900** [comment]
I've updated my code.
We probably want the SharedPreferenceListener in a separate Service.
Do you have a hint where to put that listener. This is the easy but not very clean way currently i think.

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java [hunk 1]
```diff
@@ -28,7 +32,42 @@
...
 
-    public static boolean isValidHeartRateValue(int value) {
-        return value > HeartRateUtils.MIN_HEART_RATE_VALUE && value < HeartRateUtils.MAX_HEART_RATE_VALUE;
+    private int maxHeartRateValue;
+    private int minHeartRateValue;
+
+    /**
+     * extra class used for synchronized access of the singleton
+     */
+    private static final class HeartRateUtilsInstanceHolder {
```
Comment (cpfeiffer) [inline app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java]: Can you please elaborate why we need the separate class?

If you put the static initialization directly into the `HeartRateUtils` class, this will happen at classloading time, which is perfectly synchronized. Could the static method be invoked before the static initializer is finished?

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/export/GPXExporter.java [hunk 2]
```diff
@@ -181,7 +181,7 @@ private void exportTrackpointExtensions(XmlSerializer ser, ActivityPoint point,
         long lowestDifference = 60 * 2 * 1000; // minimum distance is 2min
         for (ActivityPoint pointItem : trackPoints) {
             int hrItem = pointItem.getHeartRate();
-            if (HeartRateUtils.isValidHeartRateValue(hrItem)) {
+            if (HeartRateUtils.getInstance().isValidHeartRateValue(hrItem)) {
```
Comment (cpfeiffer) [inline app/src/main/java/nodomain/freeyourgadget/gadgetbridge/export/GPXExporter.java]: Same here, remember it outside the loop.

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java [hunk 3]
```diff
@@ -28,7 +32,42 @@
...
+    public int getMaxHeartRate(){
+        return maxHeartRateValue;
+    }
+
+    public int getMinHeartRate(){
+        return minHeartRateValue;
+    }
+
+    public boolean isValidHeartRateValue(int value) {
+        return value > getMinHeartRate() && value < getMaxHeartRate();
```
Comment (cpfeiffer) [inline app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java]: Nitpicking, but shouldn't this be `>=` and `<=`?

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java [hunk 4]
```diff
@@ -28,7 +32,42 @@
...
+     * Singleton - to access this class use the static #getInstance()
+     */
+    private HeartRateUtils() {
+        updateCachedHeartRatePreferences();
+    }
+
+    public void updateCachedHeartRatePreferences(){
+        Prefs prefs = GBApplication.getPrefs();
+        maxHeartRateValue = prefs.getInt("chart_max_heart_rate", MAX_HEART_RATE_VALUE);
+        minHeartRateValue = prefs.getInt("chart_min_heart_rate", MIN_HEART_RATE_VALUE);
```
Comment (cpfeiffer) [inline app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java]: Can you add those preference keys to `GBPrefs` and use them instead of scattering the keys? I know we have more of those, but I'd like to have fewer of them, not more :-)

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractChartFragment.java [hunk 5]
```diff
@@ -512,7 +510,7 @@ protected void refresh() {
                         }
                         activityEntries.add(createLineEntry(value, ts));
                 }
-                if (hr && sample.getKind() != ActivityKind.TYPE_NOT_WORN && HeartRateUtils.isValidHeartRateValue(sample.getHeartRate())) {
+                if (hr && sample.getKind() != ActivityKind.TYPE_NOT_WORN && HeartRateUtils.getInstance().isValidHeartRateValue(sample.getHeartRate())) {
```
Comment (cpfeiffer) [inline app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractChartFragment.java]: Not sure if the getInstance() call would be optimized by the runtime or art. We could remember the instance outside the loop.

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java (hunk 1 above)
Comment (Dikay900) [reply app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java]: This is used to be synchronized when calling HeartRateUtils.getInstance() the first time in two different threads (race condition).
This will lazy load the instance when the class is loaded.

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/export/GPXExporter.java (hunk 2 above)
Comment (Dikay900) [reply app/src/main/java/nodomain/freeyourgadget/gadgetbridge/export/GPXExporter.java]: yes this should be cleaner this way. Will rework this.

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractChartFragment.java (hunk 5 above)
Comment (Dikay900) [reply app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractChartFragment.java]: yes this should be cleaner this way. Will rework this.

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java (hunk 3 above)
Comment (Dikay900) [reply app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java]: yes you are right, just rewrote the exisiting function. Will change this as well.

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java (hunk 4 above)
Comment (Dikay900) [reply app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java]: Ok did that.

**Comment by Dikay900** [comment]
updated and squashed last commit

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java (hunk 1 above)
Comment (cpfeiffer) [reply app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java]: AFAICS we don't need any synchronization here. If we would lazily create the instance inside the `getInstance()` method, then this would need to be synchronized. But we create the instance at classloading time already (in the static initializer), so no need for any further synchronization, nor for the inner class.

File: app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java [hunk 6]
```diff
@@ -784,6 +785,9 @@ public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, Strin
                 mDeviceSupport.setAutoReconnect(autoReconnect);
             }
         }
+        if (key.equals("chart_max_heart_rate") || key.equals("chart_min_heart_rate")) {
```
Comment (cpfeiffer) [inline app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java]: Use the constant from `GBPrefs` here? :-)

Comment (Dikay900) [reply app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java]: yes you are correct <.< i shouldn't miss such things.
thanks

**Comment by Dikay900** [comment]
Ok thanks for your comments, updated again.

**Comment by cpfeiffer** [comment]
Woohoo :tada: :smile:

**Comment by xandro0777** [comment]
Just a guess, with the optical sensor it seems next to impossible to measure any HR value under 30. To get a reasonable measurement I would think the sensor must read detect at least 4 beats and I have never seen the LEDs lightning for longer than a few seconds unless in continuous mode.
